apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgclusters.pg.percona.com
spec:
  group: pg.percona.com
  names:
    kind: Pgcluster
    listKind: PgclusterList
    plural: pgclusters
    singular: pgcluster
  scope: Namespaced
  versions:
  - name: v1
    storage: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              clustername: { type: string }
              ccpimage: { type: string }
              ccpimagetag: { type: string }
              database: { type: string }
              exporterport: { type: string }
              name: { type: string }
              pgbadgerport: { type: string }
              port: { type: string }
          status:
            x-kubernetes-preserve-unknown-fields: true
            type: object
            properties:
              state: { type: string }
              message: { type: string }
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: perconapgclusters.pg.percona.com
spec:
  group: pg.percona.com
  names:
    kind: PerconaPGCluster
    listKind: PerconaPGClusterList
    plural: perconapgclusters
    singular: perconapgcluster
  scope: Namespaced
  versions:
  - name: v1
    storage: true
    served: true
    schema:
      openAPIV3Schema:
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            properties:
              state: { type: string }
              message: { type: string }
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    subresources:
      status: {}
      scale:
        specReplicasPath: .spec.pgReplicas.hotStandby.size
        statusReplicasPath: .status.ready
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgtasks.pg.percona.com
spec:
  conversion:
    strategy: None
  group: pg.percona.com
  names:
    kind: Pgtask
    listKind: PgtaskList
    plural: pgtasks
    singular: pgtask
  scope: Namespaced
  versions:
  - name: v1
    storage: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              state: { type: string }
              message: { type: string }
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgreplicas.pg.percona.com
spec:
  group: pg.percona.com
  names:
    kind: Pgreplica
    listKind: PgreplicaList
    plural: pgreplicas
    singular: pgreplica
  scope: Namespaced
  versions:
  - name: v1
    storage: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            properties:
              state: { type: string }
              message: { type: string }
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pgpolicies.pg.percona.com
spec:
  group: pg.percona.com
  names:
    kind: Pgpolicy
    listKind: PgpolicyList
    plural: pgpolicies
    singular: pgpolicy
  scope: Namespaced
  versions:
  - name: v1
    storage: true
    served: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
            properties:
              state: { type: string }
              message: { type: string }
