{{- if and (( or (( .Values.secrets.primaryuser )) (( .Values.secrets.postgres )) (( .Values.secrets.pgbouncer )) (( .Values.secrets.pguser )))) (( not .Values.secrets.name)) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg-database.fullname" $ }}-users
  annotations:
    "helm.sh/hook": pre-install
  labels:
{{ include "pg-database.labels" $ | indent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
{{- if $value }}
  {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
{{- end }}
